name: Build Android APK

on: workflow_dispatch  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Build with Gradle
      run: git clone -b sjszero-patch-1 --recursive https://github.com/sjszero/wlroots-android-bridge.git && cd wlroots-android-bridge && ./gradlew assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
          name: app-debug
          path: wlroots-android-bridge/app/build/outputs/apk/debug/*.apk